# Generated by Django 5.2.6 on 2025-11-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invenzo', '0002_usuario_estado_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
