# Generated by Django 5.2.6 on 2025-11-20 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invenzo', '0003_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertas_stock', models.BooleanField(default=True)),
                ('movimientos', models.BooleanField(default=True)),
                ('productos_nuevos', models.BooleanField(default=True)),
                ('correo_alertas', models.BooleanField(default=True)),
                ('correo_movimientos', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invenzo.usuario')),
            ],
        ),
    ]
