# Generated by Django 5.2.6 on 2025-11-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invenzo', '0004_notificacionconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistema', models.CharField(default='Invenzo', max_length=100)),
                ('stock_min_global', models.PositiveIntegerField(default=5)),
                ('stock_max_global', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='inventario/'),
        ),
    ]
