# Generated by Django 5.2.6 on 2025-11-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invenzo', '0007_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
