# Generated by Django 5.2.6 on 2025-11-21 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invenzo', '0009_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='fecha_movimiento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
