# Generated by Django 5.2.6 on 2025-12-01 16:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invenzo', '0010_alter_inventario_fecha_movimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('critico', 'Crítico'), ('bajo', 'Bajo')], max_length=10)),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('enviado_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invenzo.usuario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invenzo.producto')),
            ],
        ),
    ]
