# Generated by Django 5.2.6 on 2025-12-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invenzo', '0011_notificacionenvio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='notificado_bajo_stock',
            field=models.BooleanField(default=False),
        ),
    ]
